"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ....utils import OptionalDependencyNotAvailable, _LazyModule, is_flax_available, is_tf_available, is_torch_available
from .configuration_gptsan_japanese import GPTSanJapaneseConfig
from .tokenization_gptsan_japanese import GPTSanJapaneseTokenizer

_import_structure = ...
if not is_torch_available():
    ...
if TYPE_CHECKING:
    ...
else:
    ...
