"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ...file_utils import _LazyModule, is_torch_available, is_vision_available
from ...utils import OptionalDependencyNotAvailable
from .configuration_zoedepth import ZOEDEPTH_PRETRAINED_CONFIG_ARCHIVE_MAP, ZoeDepthConfig

_import_structure = ...
if not is_torch_available():
    ...
if not is_vision_available():
    ...
if TYPE_CHECKING:
    ...
else:
    ...
