"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ...utils import OptionalDependencyNotAvailable, _LazyModule, is_tf_available, is_torch_available
from .configuration_data2vec_audio import Data2VecAudioConfig
from .configuration_data2vec_text import Data2VecTextConfig, Data2VecTextOnnxConfig
from .configuration_data2vec_vision import Data2VecVisionConfig, Data2VecVisionOnnxConfig

_import_structure = ...
if not is_torch_available():
    ...
if is_tf_available():
    ...
if TYPE_CHECKING:
    ...
else:
    ...
