"""
This type stub file was generated by pyright.
"""

from PIL import Image
from ..models.auto import AutoModelForVisualQuestionAnswering, AutoProcessor
from .tools import PipelineTool

class ImageQuestionAnsweringTool(PipelineTool):
    default_checkpoint = ...
    description = ...
    name = ...
    pre_processor_class = AutoProcessor
    model_class = AutoModelForVisualQuestionAnswering
    inputs = ...
    output_type = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def encode(self, image: Image, question: str):
        ...
    
    def forward(self, inputs):
        ...
    
    def decode(self, outputs):
        ...
    


