"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Dict, List, Optional
from ..pipelines.base import Pipeline

class MessageRole(str, Enum):
    USER = ...
    ASSISTANT = ...
    SYSTEM = ...
    TOOL_CALL = ...
    TOOL_RESPONSE = ...
    @classmethod
    def roles(cls): # -> list[str]:
        ...
    


def get_clean_message_list(message_list: List[Dict[str, str]], role_conversions: Dict[str, str] = ...): # -> list[Any]:
    """
    Subsequent messages with the same role will be concatenated to a single message.

    Args:
        message_list (`List[Dict[str, str]]`): List of chat messages.
    """
    ...

llama_role_conversions = ...
class HfApiEngine:
    """This engine leverages Hugging Face's Inference API service, either serverless or with a dedicated endpoint."""
    def __init__(self, model: str = ...) -> None:
        ...
    
    def __call__(self, messages: List[Dict[str, str]], stop_sequences: List[str] = ..., grammar: Optional[str] = ...) -> str:
        ...
    


class TransformersEngine:
    """This engine uses a pre-initialized local text-generation pipeline."""
    def __init__(self, pipeline: Pipeline) -> None:
        ...
    
    def __call__(self, messages: List[Dict[str, str]], stop_sequences: Optional[List[str]] = ..., grammar: Optional[str] = ...) -> str:
        ...
    


DEFAULT_JSONAGENT_REGEX_GRAMMAR = ...
DEFAULT_CODEAGENT_REGEX_GRAMMAR = ...
