"""
This type stub file was generated by pyright.
"""

from ..models.auto import AutoModelForSeq2SeqLM, AutoTokenizer
from .tools import PipelineTool

LANGUAGE_CODES = ...
class TranslationTool(PipelineTool):
    """
    Example:

    ```py
    from transformers.agents import TranslationTool

    translator = TranslationTool()
    translator("This is a super nice API!", src_lang="English", tgt_lang="French")
    ```
    """
    lang_to_code = ...
    default_checkpoint = ...
    description = ...
    name = ...
    pre_processor_class = AutoTokenizer
    model_class = AutoModelForSeq2SeqLM
    inputs = ...
    output_type = ...
    def encode(self, text, src_lang, tgt_lang):
        ...
    
    def forward(self, inputs):
        ...
    
    def decode(self, outputs):
        ...
    


