"""
This type stub file was generated by pyright.
"""

import torch
from ..utils import is_torch_available
from ..utils.quantization_config import QuantizationConfigMixin
from .base import HfQuantizer

if is_torch_available():
    ...
logger = ...
class CompressedTensorsHfQuantizer(HfQuantizer):
    """
    Quantizer for the compressed_tensors package.  Loads and restores models to
    quantized state with compressed_tensors
    """
    requires_calibration = ...
    required_packages = ...
    def __init__(self, quantization_config: QuantizationConfigMixin, **kwargs) -> None:
        ...
    
    def validate_environment(self, *args, **kwargs): # -> None:
        ...
    
    def update_torch_dtype(self, torch_dtype: torch.dtype) -> torch.dtype:
        ...
    
    @property
    def is_trainable(self): # -> Literal[False]:
        ...
    
    def is_serializable(self, safe_serialization=...): # -> Literal[False]:
        ...
    


