"""
This type stub file was generated by pyright.
"""

import functools
from dataclasses import dataclass
from .image_processing_utils import BaseImageProcessor
from .utils.import_utils import is_torchvision_available
from torchvision.transforms import Compose

if is_torchvision_available():
    ...
@dataclass(frozen=True)
class SizeDict:
    """
    Hashable dictionary to store image size information.
    """
    height: int = ...
    width: int = ...
    longest_edge: int = ...
    shortest_edge: int = ...
    max_height: int = ...
    max_width: int = ...
    def __getitem__(self, key): # -> Any:
        ...
    


class BaseImageProcessorFast(BaseImageProcessor):
    _transform_params = ...
    @functools.lru_cache(maxsize=1)
    def get_transforms(self, **kwargs) -> Compose:
        ...
    
    def to_dict(self): # -> Dict[str, Any]:
        ...
    


