"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ...utils import OptionalDependencyNotAvailable, _LazyModule, is_sentencepiece_available, is_tokenizers_available, is_torch_available, is_vision_available
from .configuration_chameleon import ChameleonConfig, ChameleonVQVAEConfig
from .processing_chameleon import ChameleonProcessor

_import_structure = ...
if not is_torch_available():
    ...
if not is_vision_available():
    ...
if TYPE_CHECKING:
    ...
else:
    ...
