"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ...utils import _LazyModule
from .tokenization_myt5 import MyT5Tokenizer

_import_structure = ...
if TYPE_CHECKING:
    ...
else:
    ...
