"""
This type stub file was generated by pyright.
"""

def fixed_cross_entropy(source, target, num_items_in_batch: int = ..., ignore_index: int = ..., **kwargs): # -> Tensor:
    ...

def ForCausalLMLoss(logits, labels, vocab_size: int, num_items_in_batch: int = ..., ignore_index: int = ..., **kwargs): # -> Tensor:
    ...

def ForSequenceClassificationLoss(labels, pooled_logits, config, **kwargs): # -> Any | Tensor:
    ...

def ForQuestionAnsweringLoss(start_logits, end_logits, start_positions, end_positions, **kwargs): # -> Tensor | None:
    ...

def ForTokenClassification(logits, labels, config, **kwargs): # -> Tensor:
    ...

LOSS_MAPPING = ...
