"""
This type stub file was generated by pyright.
"""

from ..utils import DummyObject

class BaseImageProcessorFast(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class ViTImageProcessorFast(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


